const list=document.querySelector('#article-list');
if(list) list.innerHTML=ARTICLES.map((a,i)=>`<a class="article-card" href="article.html?slug=${a.slug}"><span class="num">0${i+1}</span><div><h3>${a.title}</h3><p>${a.dek}</p></div><span class="meta">${a.category}<br>${a.reading}</span><b>↗</b></a>`).join('');
const dialog=document.querySelector('#demo-dialog'),content=document.querySelector('#demo-content');
document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>openDemo(b.dataset.demo));
document.querySelector('.dialog-close').onclick=()=>dialog.close();
function openDemo(kind){content.innerHTML=kind==='docflow'?docflowDemo():devagentDemo();dialog.showModal();if(kind==='docflow') extractDoc();}
function docflowDemo(){return `<div class="demo"><small>DOCFLOW AI · INTERACTIVE PROTOTYPE</small><h2>文档结构化工作台</h2><p class="lead">修改左侧文本，再点击提取。所有处理都在当前浏览器完成。</p><div class="demo-grid"><div class="demo-panel"><label>原始文档</label><textarea id="raw-doc">增值税电子发票\n发票号码: INV-2026-0713\n开票日期: 2026-07-13\n销售方: 上海星河科技有限公司\n购买方: 阿贝贝创新工作室\n金额: 12,800.00\n税额: 768.00\n价税合计: 13,568.00</textarea><button class="btn" onclick="extractDoc()">重新提取字段</button></div><div class="demo-panel"><label>待人工复核 · <span id="field-count"></span></label><div id="fields"></div><button class="btn" onclick="exportDoc()">导出 JSON</button></div></div></div>`}
const specs=[['发票号码',/(?:发票号码|Invoice No)[:：\s]*([^\n]+)/i],['日期',/(?:开票日期|Date)[:：\s]*([^\n]+)/i],['供应商',/(?:销售方|供应商|Vendor)[:：\s]*([^\n]+)/i],['购买方',/(?:购买方|Buyer)[:：\s]*([^\n]+)/i],['金额',/(?:金额|Amount)[:：\s¥￥]*([\d,.]+)/i],['税额',/(?:税额|Tax)[:：\s¥￥]*([\d,.]+)/i],['价税合计',/(?:价税合计|Total)[:：\s¥￥]*([\d,.]+)/i]];
function extractDoc(){const raw=document.querySelector('#raw-doc')?.value||'';const data=specs.map(([k,r])=>({key:k,value:(raw.match(r)||[])[1]?.trim()||'',confidence:raw.match(r)?.[1]?96:0}));window.docData=data;document.querySelector('#field-count').textContent=`识别 ${data.filter(x=>x.value).length} 个字段`;document.querySelector('#fields').innerHTML=data.map((x,i)=>`<div class="field-row"><label>${x.key}</label><input value="${x.value}" onchange="docData[${i}].value=this.value"><small>${x.confidence}%</small></div>`).join('')}
function exportDoc(){const blob=new Blob([JSON.stringify({reviewed_at:new Date().toISOString(),fields:docData},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='docflow-result.json';a.click()}
function devagentDemo(){return `<div class="demo"><small>DEVAGENT HUB · INTERACTIVE PROTOTYPE</small><h2>从 Issue 到可审查方案</h2><p class="lead">输入任务，智能体生成透明执行计划。演示不会修改任何真实仓库。</p><div class="demo-grid"><div class="demo-panel"><label>Issue 标题</label><input id="issue-title" value="修复空用户名导致的问候异常"><label>验收条件</label><textarea id="criteria">清理用户输入；空值使用默认名称；添加回归测试。</textarea><button class="btn" onclick="planTask()">生成执行方案</button></div><div class="demo-panel" id="agent-output"><p class="lead">点击按钮开始规划。</p></div></div></div>`}
function planTask(){const title=document.querySelector('#issue-title').value;document.querySelector('#agent-output').innerHTML=`<label>任务计划 · LOW RISK</label>${['理解 Issue 与验收条件','定位影响模块和现有测试','生成最小代码变更','运行检查，等待人工批准'].map((s,i)=>`<div class="plan-step ${i<3?'done':''}"><b>${i<3?'✓':'○'} ${s}</b><span>${i===0?title:i===3?'不会自动推送代码':'已完成上下文分析'}</span></div>`).join('')}<div class="patch">+ clean_name = (name or "friend").strip()\n+ return f"Hello, {clean_name}!"\n\n+ def test_empty_name():\n+     assert greeting("") == "Hello, friend!"</div><p><button class="btn" onclick="this.textContent='✓ 已批准';this.disabled=true">批准方案</button></p>`}
